site_name: projects/cw-foo
theme:
  name: material
  palette:
    scheme: default
    primary: white
  features:
    - navigation.tabs
nav:
  Overview: index.md
  Modules:
    - modules/index.md
    - modules/index.ts.md
